### ISSUE TITLE
getting error in latest version  react native

### ISSUE THREAD

**Issue by anshumanburman** [mjinkens1/react-native-circle-list#18]
![Simulator Screen Shot - iPhone 11 - 2020-05-04 at 13 59 11](https://user-images.githubusercontent.com/28042275/80950853-4ec14300-8e14-11ea-8771-76ce42435d6e.png)

**Comment by dalewesdorp** [comment]
Same error for me

**Comment by shanu8011726** [comment]
Yes I am also getting this error. Is this beacuase of mockdata or react-native version ? Can someone please point out the solution for this.

**Comment by mjinkens1** [comment]
Pushed an update to fix this, please let me know if you are still having issues.

**Comment by shanu8011726** [comment]
**I have taken the update , by reinstalling the dependency . But I am still getting below Error. Also I am using the mockdata file from eample folder for testing** 


undefined is not an object (evaluating 'transforms["scale" + index]')
- node_modules\react-native-circle-list\src\CircleListLayout.js:17:29 in displayData.map$argument_0
* [native code]:null in map
- node_modules\react-native-circle-list\src\CircleListLayout.js:16:8 in CircleListLayout
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:10696:27 in renderWithHooks 
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:13481:6 in mountIndeterminateComponent
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20488:8 in beginWork$$1     
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19370:24 in performUnitOfWork
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19347:39 in workLoopSync    
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18997:22 in renderRoot      
* [native code]:null in renderRoot
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18709:28 in runRootCallback 
* [native code]:null in runRootCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5642:32 in runWithPriority$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5638:22 in flushSyncCallbackQueueImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:5627:28 in flushSyncCallbackQueue
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18796:28 in batchedUpdates$1- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2709:30 in batchedUpdates   
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:2870:28 in receiveTouches   
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue

**Comment by mjinkens1** [comment]
Have you cleared your npm/yarn/watchman caches, or removed and reinstalled node_modules?

**Comment by dalewesdorp** [comment]
Working properly right now, thanks for the quick fix, starred and following!

**Comment by mjinkens1** [comment]
Thanks!

**Comment by dalewesdorp** [comment]
Thanks for the awesome circle list. What would be the best way call a method on ScrollEnd to execute with regards to the index of the item that is at the top at that time?

**Comment by shanu8011726** [comment]
> Have you cleared your npm/yarn/watchman caches, or removed and reinstalled node_modules? This is working on a fresh project for me, version 0.1.33.

I am developing the app using expo. and this is my package.json file, Please let me know what changes i have to do to make it work. I dont have watman file in the project explorer , but can you please tell me the proper way to clear [cache.](url
![image](https://user-images.githubusercontent.com/24874288/81060525-88ed1c00-8eca-11ea-8305-c3bd148bd88c.png)
)

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "aws-amplify": "^2.2.7",
    "aws-amplify-react-native": "^3.2.2",
    "expo": "~36.0.0",
    "expo-av": "~8.0.0",
    "expo-camera": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-linear-gradient": "~8.0.0",
    "expo-permissions": "~8.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-circle-list": "^0.1.33",
    "react-native-circular-action-menu": "^0.5.0",
    "react-native-collapsible": "^1.5.2",
    "react-native-confirmation-code-input": "^1.0.4",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.5.5",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-otp-inputs": "^5.0.1",
    "react-native-reanimated": "~1.2.0",
    "react-native-screens": "^2.4.0",
    "react-native-size-matters": "^0.3.0",
    "react-native-unordered-list": "^1.0.4",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.8.13"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.0.0",
    "@babel/core": "^7.0.0"
  },
  "private": true
}

**Comment by mjinkens1** [comment]
@dalewesdorp So you're basically wanting to fire the onScrollEnd event whenever an element at a certain index is at the top of the list?  Off the top of my head I think that might require adding a new API to the component.  If you want to open a feature request issue I can take a look into it, but  it might be a while before I have time for new features unfortunately.

**Comment by mjinkens1** [comment]
@shanu8011726 I'm not super familiar with expo and what additional tooling there is on top of RN, but this link may be helpful for clearing your caches.  https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352
