### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by songxiaoliang** [mjinkens1/react-native-circle-list#2]
![Simulator Screen Shot - iPhone Xʀ - 2019-07-26 at 14 28 16](https://user-images.githubusercontent.com/6975588/61930853-a42d1180-afb1-11e9-83a2-2a7df45ee78c.png)

**Comment by mjinkens1** [comment]
Hi, can you please provide code/a set of steps to reproduce this issue?

**Comment by songxiaoliang** [comment]
@mjinkens1 Ok, This error will only appear on iPhoneX and above and on the Android platform.
`<CircleList`
    `elementCount={16}`
    `flatness={0.03}`
    `radius={320 / 2}`
    `data={[1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6]}`
    `renderItem={this.renderItem}`
    `keyExtractor={this.keyExtractor}`
    `innerRef={(component) => { this.circleList = component; }}`
    `onScrollEnd={() => this.circleList.scrollToIndex(this.progressIndex)}`
`/>`

**Comment by songxiaoliang** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2019-07-29 at 09 56 27](https://user-images.githubusercontent.com/6975588/62016904-2f431d00-b1e7-11e9-9604-5f06872da33a.png)

**Comment by songxiaoliang** [comment]
@mjinkens1 Hey, I found this error after I set the radius property.

**Comment by songxiaoliang** [comment]
@mjinkens1 After setting the radius, I found the following code will appear the value of translateX or translateY is Null

` _getTransforms = index => {` 
        ` const { flatness, radius } = this.props` 
        ` const { theta } = this.state` 

        ` const thetaOffset = 2 * PI * index + (this.rotationOffset + ROTATION_OFFSET)` 
        ` const translateX = radius * cos(index * theta + thetaOffset)` 
        ` const translateY =` 
            ` (1 - flatness) * radius * sin(index * theta + thetaOffset) + (1 - flatness) * radius` 

       ` return { translateX, translateY }` 
   `  }`

**Comment by songxiaoliang** [comment]
@mjinkens1 I also found a problem, the elementCount element should be declared before displayData
`this.state = {`
           ` .....`

            `displayData: this._getOffsetData(dataWithIndexes, elementCountWithMin),`
            `elementCount: elementCountWithMin,`
           `.....`
` }`

**Comment by songxiaoliang** [comment]
@mjinkens1 The problem has been solved, thanks
